const listUser = [
  {
    id: 5,
    email: "username1@gmail.com",
    user: "hungnt",
    pass: "123",
    address: "gfjhsafkjsd",
    phone: "0123456789",
    role: "user",
  },
  {
    id: 1,
    email: "username1@gmail.com",
    user: "username1",
    pass: "123tnvn",
    address: "gfjhsafkjsd",
    phone: "0123456789",
    role: "user",
  },
  {
    id: 2,
    email: "username2@gmail.com",
    user: "username2",
    pass: "123tnvn1",
    address: "gfjhsafkjsd",
    phone: "0123456786",
    role: "user",
  },
  {
    id: 3,
    email: " username3@gmail.com",
    user: "username3",
    pass: "123tnvn2",
    address: "gfjhsafkjsd",
    phone: "0123456787",
    role: "user",
  },
  {
    id: 4,
    email: " username4@gmail.com",
    user: "username4",
    pass: "123tnvn3",
    address: "gfjhsafkjsd",
    phone: "0123456788",
    role: "hotel",
  },
];
