const listUser = [
  {
    id: 5,
    name: "Nguyen The Hung",
    email: "hungnt.se@gmail.com",
    user: "hungnt",
    pass: "123",
    phone: "0123456789",
    role: "user",
  },
  {
    id: 1,
    name: "User Two",
    email: "username1@gmail.com",
    user: "username1",
    pass: "123tnvn",
    phone: "0123456789",
    role: "user",
  },
  {
    id: 2,
    name: "User Three",
    email: "username2@gmail.com",
    user: "username2",
    pass: "123tnvn1",
    phone: "0123456786",
    role: "user",
  },
  {
    id: 3,
    name: "User Four",
    email: "username3@gmail.com",
    user: "username3",
    pass: "123tnvn2",
    phone: "0123456787",
    role: "user",
  },
  {
    id: 4,
    name: "User Five",
    email: "username4@gmail.com",
    user: "username4",
    pass: "123tnvn3",
    phone: "0123456788",
    role: "hotel",
  },
];
